# Generated by Django 3.1.5 on 2021-01-06 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
    ]
